### ISSUE TITLE
Example Vagrantfile for a repository containing shell.nix

### ISSUE THREAD

**Issue by knedlsepp** [zimbatm/nixbox#19]
I'm in the situation that I have defined a "shell.nix" file inside one of my projects. I would like to be able to set up a `Vagrantfile`, which uses your nixbox and automatically drops you in a `nix-shell` for the specified file on `vagrant up; vagrant ssh`.
Is this use case possible using your nixbox?

**Comment by zimbatm** [comment]
You could replace `/home/vagrant/.bashrc` with something like:

```sh
if [[ -z $PS1 ]]; then return; fi # for scp and friends
if [[ -z $IN_NIX_SHELL ]]; then exec nix-shell /vagrant; fi

# the usual stuff here
```

When the user runs `vagrant ssh` it will log him into bash and automatically start nix-shell, which loads back again but this time skips the second branch.

**Comment by knedlsepp** [comment]
Thank you for the great solution!
