### ISSUE TITLE
17.03 release

### ISSUE THREAD

**Issue by PierreR** [zimbatm/nixbox#22]
Hi,

I have everything ready for 17.03 locally. It is working nicely (tested for x84). My sole question is about the atlas extra bit that have been regenerated again. Do you want me to push with or without it ?

**Comment by zimbatm** [comment]
Hi PierreR,

This repo depends on the atlas bit to build the images automatically so it can't really be removed.

According to https://github.com/mitchellh/packer/issues/2679 the best solution is to generate two files, one with the post-processor and one without. That's not ideal but seems like a reasonable alternative.

**Comment by PierreR** [comment]
Then it is back in again for now.
